name: "refresh"
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: 
      - completed
  push:
    paths:
      - 'debs/**/*.deb'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
      - name: Install Dependencies
        if: success()
        run: |
          sudo apt update -qq
          sudo apt install dpkg-dev bzip2 xz-utils zstd -y
      - name: Refresh Packages
        if: success()
        run: |
          mkdir -p repo
          rm -rf ./repo/Packages*
          dpkg-scanpackages -a -m ./debs /dev/null >./repo/Packages
          bzip2 -v -k -9 ./repo/Packages
          xz -v -k -9 --extreme ./repo/Packages
          zstd --ultra -22 -k ./repo/Packages -o ./repo/Packages.zst
          cat > ./repo/Release << EOF
Origin: crctdd Repo
Label: crctdd Repo
Suite: stable
Codename: ios
Architectures: iphoneos-arm iphoneos-arm64 iphoneos-arm64e
Components: main
Description: crctdd Repo
EOF
      - name: Configure Git
        if: success()
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
      - name: Commit Changes
        if: success()
        run: |
          git add .
          if ! git diff --staged --exit-code 1>>/dev/null; then
            git commit -m 'Refresh Packages (sync all versions)'
          fi
      - name: Push Changes
        if: success() && github.ref == 'refs/heads/main'
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin main
      - name: Download remove_all_actions
        if: success()
        run: |
          sudo curl -L -o '/usr/bin/remove_all_actions' 'https://raw.githubusercontent.com/invalidunit/action/main/remove_all_actions'
          sudo chmod -R 0755 '/usr/bin/remove_all_actions'
      - name: Remove All Old Actions
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          remove_all_actions
