name: Build Repo

on:
  push:
    paths:
      - 'debs/**/*.deb'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dpkg tools
      run: |
        sudo apt update
        sudo apt install dpkg-dev -y

    - name: Generate Packages
      run: |
        mkdir -p repo
        dpkg-scanpackages debs /dev/null > repo/Packages
        gzip -kf repo/Packages

    - name: Generate Release
      run: |
        cat > repo/Release << EOF
Origin: crctdd Repo
Label: crctdd Repo
Suite: stable
Codename: ios
Architectures: iphoneos-arm iphoneos-arm64 iphoneos-arm64e
Components: main
Description: crctdd Repo
EOF

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: repo

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
